### ISSUE TITLE
Improve audio buffering behavior

### ISSUE THREAD

**Issue by phanan** [koel/player#15]
- [ ] Display an indicator for buffering status
- [ ] Shows the Now Playing sheet even if the song is only being buffered.

**Comment by brijrajcodisto** [comment]
Hi Phanan, I want to work on this issue and resolve it.

**Comment by phanan** [comment]
Sure!

**Comment by brijrajcodisto** [comment]
I have resolved 1st part - "Display an indicator for buffering status"
Here is the PR - https://github.com/koel/player/pull/52

**Comment by brijrajcodisto** [comment]
About second part - "Shows the Now Playing sheet even if the song is only being buffered."
Will the now playing will have title of song also while buffering ?

**Comment by phanan** [comment]
> Will the now playing will have title of song also while buffering ?

Preferrably yes. WDYT?

**Comment by brijrajcodisto** [comment]
yes, I have implemented this as well.
