### ISSUE TITLE
Can't play any song "The network connection was lost"

### ISSUE THREAD

**Issue by card1127** [koel/player#42]
I enjoy music life by koel and bought Koel Player.
Thank you for your developing!
But, I have one problem so I report you.

I have many mp3 songs and can play by Chrome on Mac.
But, I can't play any mp3 song by Koel Player on iPhone.

I tried on iOS Simulator, I caught following error
```
PlatformException (PlatformException(PLAY_ERROR, Cannot play http://192.168.xxx.xxx:8000/play/30c8123xxxxxxxxx?api_token=xx%7CH3Yxxxxxxxx, The network connection was lost., null))
``` 

at

```
lib/providers/audio_provider.dart:85 -> await _player.playlistPlayAtIndex(index);
and
lib/ui/widgets/song_row.dart:62 -> onTap: () async => await audio.play(song: widget.song),
```

This exception is not on iPhone screen and continue app.
Server has no error.

If you know, please tell me resolve method.

Best Regards,

Server
Mac mini M1
macOS 11.5.2
php 7.4.22
mysql 8.0.25
koel version(tag) 5.1.5

Player
iOS14.7.1
iPhone se 2nd Gen
App Version 1.0.1

<img width="1720" alt="スクリーンショット 2021-08-15 1 16 09" src="https://user-images.githubusercontent.com/16831448/129452707-8a5620cb-70e5-40c6-83c7-4f7251c73b48.png">

**Comment by phanan** [comment]
Your server should support HTTPS ;)
