### ISSUE TITLE
Shuffle Button functionality.

### ISSUE THREAD

**Issue by adsingh14** [koel/player#47]
Need 'Shuffle' button functionality.

**Before**
![image](https://user-images.githubusercontent.com/35252877/136662232-30bf7cd4-84b1-450e-9119-e6190dcb796e.png) 

**After**
![image](https://user-images.githubusercontent.com/35252877/136662298-eba289fe-402c-4247-824d-b0e3c806dc7e.png)

I can add the the UI functionality.

**Comment by phanan** [comment]
Hey there, looks like you've posted in the wrong repository. Nevertheless, this feature is already a thing.
