### ISSUE TITLE
IOS APP UI ISSUE

### ISSUE THREAD

**Issue by PotatoYummy** [koel/player#48]
![微信截图_20211011203344](https://user-images.githubusercontent.com/86452004/136790626-4a94d5e8-dcb6-4c49-b849-86dc1cafa3d2.png)
As shown in the screenshot above
There will be endless blank backgrounds after the homepage tab is swiped up, which is terrible.

Koel v1.1.0
IOS 15.0.1

The program is very good, there are still some suggestions for reference:
1. Hope to support multiple languages, such as Chinese
2. The app price is too expensive, not conducive to promotion.As a KOEL user, I am willing to pay this price, but when I share my music with my friends, they don’t think so.

**Comment by phanan** [comment]
Sorry for the late response. The overflow problem should have been fixed in the recent versions. Translations would be an issue, as I don't speak any foreign language other than English. For the price, well, you only pay once in comparison to monthly subscription services, so… 😄
