### ISSUE TITLE
Downloaded Songs dissapear after time on IOS

### ISSUE THREAD

**Issue by pandalanax** [koel/player#51]
Hi, i noticed that my downloaded songs are deleted after a while, so that i have to redownload them. 
Not sure about the interval of this error. sometimes it takes two minutes and the songs are gone, sometimes 2 days. 

I host the koel docker image with a mysql server container.
and big thanks to you, i'm really enjoying koel!

**Comment by phanan** [comment]
I've extended the cache expiry, but downloads from Koel still share the same cache policy by the OS and are subject to cleaning up.
