### ISSUE TITLE
Idea: Sync Library & Widgets

### ISSUE THREAD

**Issue by sylphrena0** [koel/player#56]
I would like to have my entire library synced with a local copy on the app. I'd rather not download all 2000 songs manually, so it would be amazing to have an option to enable this sort of sync.

Could you also add an option to store music files on SD cards?

Also, it would be awesome to have widgets. I'm quite attached to the 5x1 widgets from my old music app and would really like to see them here.

**Comment by Muhand** [comment]
Where you store music doesn't really matter. What matters is the folder your server is watching. You can have your music server on SD card as long as your server is watching that SD card. Same applies to syncing.
