### ISSUE TITLE
[Bug] [Feedback] koel android application 

### ISSUE THREAD

**Issue by kevincaradant** [koel/player#57]
Hi

It's just to give my firsts feedback about the application recently bought.

It's really nice, I like it globally, nice work!
However, I have some remarks.

1) the application doesn't stop to play music after that I disconnect my bluetooth device.
I have all my others music's application which stop to play the current music when my BT device is switch off. Here, koel continue to play music :/

2) bug really weird, sometimes, one time by day, when I click on a music and then I click on it again or even on an other music, the previous one is not cancelled, and koel start the new one over the old one. If I click 5 times, I have 5 music's which are running in the same time 😂.
The problem is when I click on pause or stop. I saw that it's only applied to the last music started. So I have to hard kill the app and start it again. But as I said it's not all the time, I don't know how I get this issue.

3) on the home page, in the 'most played songs' ect, I would have the possibility to go on the album directly clicking on it. Today, the current behavior is just to start the music where I clicked. But it doesn't open the album. Have some shortcut like this could be very interesting. 

4) and to finish, I didn't know if its on the roadmap, but I have difficulties to accept to have several same album with a album for each feat. Is there a way to have all the albums directly into one, without to have 4 albums with 3 albums containing only one song because there is only one feat? 

Thank you for advices on this

Regards

**Comment by kevincaradant** [comment]
Hi @phanan it's me again

What do you think about the possible fixes ? And you point of view about the (point 4) 

Thank you

**Comment by Streametch** [comment]
Can confirm bug #2, double play issue exist

**Comment by phanan** [comment]
Thanks! I've submitted v2 with lots of improvements and fixes :)
