### ISSUE TITLE
Error: flutter_math_fork is missing implementation

### ISSUE THREAD

**Issue by shoaibali** [koel/player#58]
Flutter 2.9.0-0.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 8f1f9c10f0 (2 weeks ago) • 2021-12-14 13:41:48 -0800
Engine • revision 234aca678a
Tools • Dart 2.16.0 (build 2.16.0-80.1.beta) • DevTools 2.9.1

`
flutter build apk
Running "flutter pub get" in player...                              4.7s

💪 Building with sound null safety 💪

../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3+1/lib/src/widgets/selectable.dart:407:7: Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InternalSelectableMathState extends State<InternalSelectableMath>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/packages/flutter/lib/src/services/text_input.dart:1034:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
../../snap/flutter/common/flutter/packages/flutter/lib/src/services/text_input.dart:1014:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
../../snap/flutter/common/flutter/packages/flutter/lib/src/services/text_input.dart:1022:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
../../snap/flutter/common/flutter/packages/flutter/lib/src/services/text_input.dart:1028:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/home/shoaib/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/shoaib/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
Running Gradle task 'assembleRelease'...                           34.9s
Gradle task assembleRelease failed with exit code 1

`

To resolve have to run

`flutter pub upgrade --major-versions`

**Comment by Muhand** [comment]
The proposed solution might work but it is not ideal. It can create issues especially if the new version of the other dependencies is not compatible.

A better solution is as follows:
1. Edit `pubspec.yaml`
2. Replace the line `provider: ^5.0.0` with `provider: ^6.0.0`
3. Add the line `flutter_math_fork: ^0.5.0`

This will ensure to update only the needed dependencies.

**Comment by AlessandroZanatta** [comment]
Your fixes are not working for me. I tried from both the last release and the current master branch. Here's the error AFTER the fixes:

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
../../.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Running Gradle task 'assembleRelease'...                           28.4s
Gradle task assembleRelease failed with exit code 1
```
I know absolutely nothing about flutter, so feel free to ask for more details, if you are willing to help.

**Comment by AlessandroZanatta** [comment]
@Muhand I've put together a Dockerfile to reproduce the above error. I've also tried the different releases of Koel player. None build. Moreover, I've tried solving the error... but that was creating new errors... and solving them created even more errors.

```dockerfile
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install git curl unzip android-sdk wget -y

WORKDIR /
# Flutter
RUN git clone https://github.com/flutter/flutter.git -b stable
ENV PATH="${PATH}:/flutter/bin"

# sdkmanager and other sdk-tools
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O sdk-tools-linux.zip

WORKDIR /usr/lib/android-sdk
RUN unzip /sdk-tools-linux.zip
# Accept SDK licenses
RUN ls cmdline-tools -la
RUN mkdir cmdline-tools/latest/
RUN mv -t cmdline-tools/latest cmdline-tools/NOTICE.txt cmdline-tools/bin cmdline-tools/lib cmdline-tools/source.properties
RUN yes | cmdline-tools/latest/bin/sdkmanager --licenses 

# Build koel
WORKDIR /
RUN git clone https://github.com/koel/player 

WORKDIR /player
RUN sed -i '/provider/ s/5.0.0/6.0.0/' pubspec.yaml
RUN sed -i '49 a \ \ flutter_math_fork: ^0.5.0' pubspec.yaml
RUN cat --number pubspec.yaml
RUN flutter build apk --release
```

Would you mind looking into this please?

**Comment by l0l67** [comment]
same problem for me

**Comment by Muhand** [comment]
> @Muhand I've put together a Dockerfile to reproduce the above error. I've also tried the different releases of Koel player. None build. Moreover, I've tried solving the error... but that was creating new errors... and solving them created even more errors.
> 
> ```dockerfile
> FROM ubuntu:20.04
> 
> ARG DEBIAN_FRONTEND=noninteractive
> RUN apt-get update && apt-get install git curl unzip android-sdk wget -y
> 
> WORKDIR /
> # Flutter
> RUN git clone https://github.com/flutter/flutter.git -b stable
> ENV PATH="${PATH}:/flutter/bin"
> RUN flutter
> 
> # sdkmanager and other sdk-tools
> RUN wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O sdk-tools-linux.zip
> 
> WORKDIR /usr/lib/android-sdk
> RUN unzip /sdk-tools-linux.zip
> # Accept SDK licenses
> RUN ls cmdline-tools -la
> RUN mkdir cmdline-tools/latest/
> RUN mv -t cmdline-tools/latest cmdline-tools/NOTICE.txt cmdline-tools/bin cmdline-tools/lib cmdline-tools/source.properties
> RUN yes | cmdline-tools/latest/bin/sdkmanager --licenses 
> 
> # Build koel
> WORKDIR /
> RUN git clone https://github.com/koel/player 
> 
> WORKDIR /player
> RUN sed -i '/provider/ s/5.0.0/6.0.0/' pubspec.yaml
> RUN sed -i '49 a \ \ flutter_math_fork: ^0.5.0' pubspec.yaml
> RUN cat --number pubspec.yaml
> RUN flutter build apk --release
> ```
> 
> Would you mind looking into this please?

I am not an expert when it comes to flutter but I will take a look into it as soon as I can. At the end of the day 2 brains working better than 1.

**Comment by l0l67** [comment]
got it to build with a few small changes: https://github.com/l0l67/player
i added a keystore and key.properties file for testing

**Comment by AlessandroZanatta** [comment]
Thanks @l0l67 ! That's more than a few changes though, that's a lot of work done!

Here's an updated Dockerfile, if anyone's interested:
```Dockerfile
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install git curl unzip android-sdk wget -y

WORKDIR /
# Flutter
RUN git clone https://github.com/flutter/flutter.git -b stable
ENV PATH="${PATH}:/flutter/bin"
RUN flutter

# sdkmanager and other sdk-tools
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O sdk-tools-linux.zip

WORKDIR /usr/lib/android-sdk
RUN unzip /sdk-tools-linux.zip
# Accept SDK licenses
RUN ls cmdline-tools -la
RUN mkdir cmdline-tools/latest/
RUN mv -t cmdline-tools/latest cmdline-tools/NOTICE.txt cmdline-tools/bin cmdline-tools/lib cmdline-tools/source.properties
RUN yes | cmdline-tools/latest/bin/sdkmanager --licenses 

# Build koel apk
WORKDIR /
RUN git clone https://github.com/l0l67/player
WORKDIR /player
RUN flutter build apk --release

# Disclaimer: this isn't working (related to a question below)
# Make linux app
RUN apt-get update && apt-get install -y build-essential cmake make
WORKDIR /player/linux
RUN mkdir build
RUN cd build && cmake ..
```

This indeed compiles, however I can't seem to be able to login to my instance (which is behind a Wireguard VPN with custom DNS entries as I use a reverse proxy to host multiple http(s) services). With `adb logcat` I get the following:
```
06-17 10:54:11.811 26313 26331 I flutter : HandshakeException: Handshake error in client (OS Error: 
06-17 10:54:11.811 26313 26331 I flutter : 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
06-17 10:54:11.835 26313 26313 I HwSecImmHelper: mSecurityInputMethodService is null
```
However, my certificate is completely fine and not expired (browsers accept it, and it looks good when inspecting it by hand). Any idea what might be causing this?

Also, I'm interested in the GTK app as well (there seem to be one, wasn't even aware of that). CMake throws a bunch of errors:
```
CMake Error at flutter/CMakeLists.txt:7 (include):
  include could not find load file:

    /player/linux/flutter/ephemeral/generated_config.cmake


CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  flutter/CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
See also "/player/linux/CMakeFiles/CMakeOutput.log".
See also "/player/linux/CMakeFiles/CMakeError.log".
```
Could you please give me some guidance on how to properly build this? Thanks!

Thanks again for the awesome work!

P.S. Did you consider making a PR for this?

**Comment by l0l67** [comment]
The problem with the GTK app could be that you dont have pkgconfig installed (as seen in the line `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`) 

You could simply try to install it (on arch a simple `sudo pacman -S pkgconfig` should do the trick)

**Comment by AlessandroZanatta** [comment]
Yeah I got that to build just now.
The problem is, the app refuses to work correctly (no idea if that's related to your changes or not). When I try to play a song I get this error:
```
** (player:29154): CRITICAL **: 11:21:29.263: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) == 0' failed
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
#0      AudioProvider.init.<anonymous closure> (package:app/providers/audio_provider.dart:37)
#1      _rootRunUnary (dart:async/zone.dart:1434)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#5      _DelayedData.perform (dart:async/stream_impl.dart:591)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663)
#8      _rootRun (dart:async/zone.dart:1418)
#9      _CustomZone.run (dart:async/zone.dart:1328)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#12     _rootRun (dart:async/zone.dart:1426)
#13     _CustomZone.run (dart:async/zone.dart:1328)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

flutter: MissingPluginException(No implementation found for method stop on channel assets_audio_player)
flutter: MissingPluginException(No implementation found for method open on channel assets_audio_player)
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method open on channel assets_audio_player)
```

**Comment by l0l67** [comment]
It could have something to do with the newer versions of some of the plugins, i dont have the time right now to take a closer look at it but i might do it later

**Comment by phanan** [comment]
I believe this isn't an issue anymore in the latest version. If it still is, feel free to submit another bug report.
