### ISSUE TITLE
[Feature Request] Support offline access to downloaded content

### ISSUE THREAD

**Issue by Sacha-Ringenbach** [koel/player#62]
**How to reproduce** : Kill the Koel Player application and disconnect your internet access, you won't be able to access your downloaded content because you won't be able to login.

**Why** : When you need your music but you are on a plane, don't have data, or you want to use koel as a mp3 player.

**Proposed solution** : Support login even when application was killed, or add a "offline music" button on the login page.

**Comment by metalune1** [comment]
Yes please! This is the only thing holding me back from using this on my phone!

**Comment by 0x1a8510f2** [comment]
Also really hoping for this to be added as it is probably the main reason to download songs in the first place.

>Support login even when application was killed, or add a "offline music" button on the login page.

I assume the app treats all load failures as an auth issue. Should hopefully be as simple as adding a distinction between network errors and 403.

**Comment by phanan** [comment]
Thanks for the feedback! This feature has been implemented in v2. You can now use "offline mode" when starting Koel without a connection.
