### ISSUE TITLE
[Bug] Cannot exit "downloaded" tab when you have no song downloaded.

### ISSUE THREAD

**Issue by Sacha-Ringenbach** [koel/player#64]
**How to reproduce** : Use the koel player app with no song downloaded, tap the downloaded tab under library, there won't be a back button so you cannot go back on IOS, you have to restart the app.

**Proposed solution** : Add a back button.

**Comment by Muhand** [comment]
I agree with the need for a back button; However you can go back by swiping from left to right, make sure to touch the edge. It is the default behavior of Apple's `UIKit` navigation.

**Comment by phanan** [comment]
What @Muhand said :)
