### ISSUE TITLE
updated to Flutter 3.0.5 and updated libraries

### ISSUE THREAD

**Issue by aelayyuu** [koel/player#72]
I've updated this player to flutter 3.0.5 and some of packages are updated.
Please check my repo

https://github.com/aelayyuu/koel_player.git

**Comment by pattmax00** [comment]
I was having a lot of compilation errors and this fixed it, thanks!

**Comment by JaxzKyd** [comment]
IT ACTUALLY BUILT 🎉
buttt
![Screenshot_20230309_081923.jpg](https://user-images.githubusercontent.com/39567321/224035620-41f422a6-1da9-4ec9-826c-ec22cdb70cad.jpg)

😔

**Comment by pattmax00** [comment]
> IT ACTUALLY BUILT 🎉
> buttt
> ![Screenshot_20230309_081923.jpg](https://user-images.githubusercontent.com/39567321/224035620-41f422a6-1da9-4ec9-826c-ec22cdb70cad.jpg)
> 
> 😔

I had the same issue. Since the web client is so good on mobile, I just use that.

**Comment by phanan** [comment]
Please try the new v2 which includes a lot of bug fixes and improvements.
