### ISSUE TITLE
(iOS) Mobile app becomes inactive

### ISSUE THREAD

**Issue by burzaca** [koel/player#76]
When using the mobile app (iOS 16.2), having the phone locked, after some time when a song ends it doesn't start the next.
The player visible on the lock screen is blank as if nothing is playing. It only starts playing again when I unlock the phone and open the app in foreground. It doesn't happen after some defined time, to me it seems random. Sometimes it would work non-stop for an hour, other times it would stop after about 15 minutes.
image for clarification.

![IMG_2262](https://user-images.githubusercontent.com/41877467/210186922-65d0884c-21da-43c3-a2a8-978bac72ad51.jpeg)

**Comment by phanan** [comment]
Sorry for the late response. This is an acknowledged bug that should be fixed in v2.
