### ISSUE TITLE
(iOS) Mobile app becomes inactive

### ISSUE THREAD

**Issue by burzaca** [koel/player#79]
**Describe the bug**
When using the mobile app after some time it becomes inactive, until the phone is unlocked and the app is open in foreground.
Sometimes the playback continues for more than an hour, sometime it stops after some minutes. Maybe it has something to do with the background app refresh, as I do not see Koel Player in the options for it.

**To reproduce**
1. Open app and play music
2. Lock phone
3. Wait until the music stops
4. Player on lock screen becomes empty and grey, inactive.

**Expected behavior**
Uninterrupted playback

**Screenshots**
![IMG_2262](https://user-images.githubusercontent.com/41877467/210347857-031fcc96-af6f-4d07-bfa1-92daf999ae0f.jpeg)

**Environment**
 - Koel version [v6.1.0]
 - OS: [iOS 16.2]

**Comment by phanan** [comment]
Shoul be fixed in v2.

**Comment by burzaca** [comment]
Will you push the new version to the app store?

**Comment by phanan** [comment]
I have. It's currently under review by Apple.
