### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by JaxzKyd** [koel/player#80]
I'm having a problem building the app with Flutter 3.7.7, below are the logs
- [buildfail.txt](https://github.com/koel/player/files/10931244/buildfail.txt)

Any idea how to resolve this?

**Comment by JaxzKyd** [comment]
Okay, fixed the problem in the issue by running `flutter pub upgrade`, but now I got a new slew of errors
![image](https://i.imgur.com/4dpxr4D.png)
Particularly that Java one, jre1.8.0_361 isn't even available for download anymore from what I can tell? So how the hell do I work around that one

**Comment by JaxzKyd** [comment]
Okay, fixed the problem in the issue by running `flutter pub upgrade`, but now I got a new slew of errors
![image](https://i.imgur.com/4dpxr4D.png)
Particularly that Java one, I have jre1.8.0_361 installed and as the image implies, there is no tools.jar in that folder, or in the jre1.8.0_361/lib folder... so I'm just.... confused?
https://www.java.com/en/download/
This is where I installed the version from, if that helps at all in troubleshooting the problem

**Comment by phanan** [comment]
Please try v2.

**Comment by JaxzKyd** [comment]
![image](https://user-images.githubusercontent.com/39567321/230646795-738aaf25-3178-40c3-8ffc-9133b3e1470f.png)

**Comment by JaxzKyd** [comment]
After running `flutter pub upgrade`
![image](https://user-images.githubusercontent.com/39567321/230647882-f8a67a3d-1fb0-4696-aa3f-a079758f4250.png)

**Comment by phanan** [comment]
If you want to build the app bundle (`Build -> Flutter -> Build App Bundle…` in Android Studio) you'll need the signing config for the project. You can follow the guide here: https://developer.android.com/studio/publish/app-signing.

**Comment by JaxzKyd** [comment]
I'm trying to build the apk though?

**Comment by Bielecki** [comment]
I managed to build the app on WSL2. Note that I am not an Android Dev, but I have done it by trial and errors.

At first install dependencies
```
sudo apt install -y curl git unzip xz-utils zip libglu1-mesa
sudo apt install -y libc6:amd64 libstdc++6:amd64 lib32z1 libbz2-1.0:amd64
```
Download commandline tools from there: https://developer.android.com/studio and unzip it
Download Flutter v.3.24.5 from there https://docs.flutter.dev/install/archive (ref `dec2ee5`) and untar it
Add their `bin/` to PATH

---
### Issue with java
In my case I needed to download full android-studio as well, untar it and add its `bin/` to PATH as well to resolve following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':path_provider_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':path_provider_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /home/bielecki/sdk/platforms/android-34/core-for-system-modules.jar.
         > jlink executable /usr/lib/jvm/java-21-openjdk-amd64/bin/jlink does not exist.
```
If your java install provides `jlink` this step may not be necessary

---
Create temporary directory for sdk and install necessary packages:
```
mkdir /tmp/sdk
sdkmanager --sdk_root=/tmp/sdk/ "platform-tools" "platforms;android-35" "cmdline-tools;latest" "build-tools;35.0.1" "ndk;25.1.8937393"
```
Clone koel/player and go to its root dir
Change `android/app/build.gradle`:
```diff
-    compileSdkVersion 35
-    ndkVersion flutter.ndkVersion
+    compileSdkVersion 36
+    ndkVersion = "25.1.8937393"
```
Do `flutter pub upgrade`.

---
### Issue with dart

If you run build now you may encounter following error:
```
../.pub-cache/hosted/pub.dev/flutter_spinkit-5.2.2/lib/src/double_bounce.dart:77:34: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
            color: widget.color!.withValues(alpha: 0.6),
                                 ^^^^^^^^^^
```
The dirty workaround (that I found [here](https://github.com/dart-lang/dart-pad/issues/3061#issuecomment-2563350099)) is to edit referenced `double_bounce.dart` and replace `withValues` with `withOpacity` and removing `alpha: `:
```diff
-            color: widget.color!.withValues(alpha: 0.6),
+            color: widget.color!.withOpacity(0.6),
```
---

Now you can build the app (`--debug` is there to build unsigned app)
```
~/player$ flutter build apk --debug --android-skip-build-dependency-validation

Running Gradle task 'assembleDebug'...                             11.8s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
```

<img width="230" height="512" alt="Image" src="https://github.com/user-attachments/assets/9d96460f-9c21-4740-86ef-4f1f3d9bdbc3" />
