### ISSUE TITLE
Koel v2.0 Problems

### ISSUE THREAD

**Issue by Natsuk4sh1i** [koel/player#84]
I recently updated to koel 2.0 on my samsung s21+, running android 13.
The App will stop responding about 1 minute after starting it and then crash.
Also background play wont work at all and stop even earlier.

I love the new design but sadly this version is not usable at all

**Comment by lidstah** [comment]
I do have a similar problem which might be linked, although not a dealbreaker in my case, with a motorola g22, android 12.

My setup involves:

* connecting to my home's wireguard vpn (which also pushes my internal DNS server).
* connecting with Koel app to my home Koel server (hosted on my home's kubernetes cluster, https handled by ingress-nginx, let's encrypt certificates, postgresql database).
* No problem if I use Firefox for Android to connect through this setup, browsing music library and playing songs works as intended.
* No problem with Koel Android app to browse my music library but when I play the first song, it'll start playing and around 20-30 seconds later app will show the "app is not responding" window. Clicking on "Wait" solves the problem and other songs play without a hitch.

**Comment by linuxrules1** [comment]
I've had the exact same problem as well, I start playing a song and the app just crashes about a minute in. This only started happening after the 2.0 update. One thing I've also noticed is Koel media controls no longer show up on the lockscreen or in the pulldown menu like they did before, not sure if these 2 issues are related though. This issue also happens with playing both locally cached and online songs

+1 to the comment of the new design looks fantastic, but this issue makes the app completely unusable

**Comment by PermaFreez** [comment]
You guys are lucky, mine crashes in around 5 seconds after putting it in the background.
Xiaomi Redmi 8
Havoc Os 4.14, Android 11

**Comment by zv0n** [comment]
Same problem here, app crashes after a few seconds of playing a song. I also noticed that the app isn't showing up in the pull down status bar.

Android 12

**Comment by phanan** [comment]
Sorry folks, I should have tested it more thoroughly. Will work on a fix.

**Comment by phanan** [comment]
Submitted v2.0.1 on Google Play, waiting for approval.

**Comment by phanan** [comment]
@zv0n Oh, that's super fast. Thanks for the feedback, and enjoy!
